### PR TITLE
Resolve outbound proxy null checking. (fixes #20)

### LINKED ISSUE #20: Account settings does not open again if proxy field empty
ITNOA

When defining sip account, if does not fill proxy fields, (proxy fields is optional) and save configurations.

you cannot open again sip account settings

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

this PR resolved #20

### CODE REVIEW

**Comment by soroshsabz** [comment]
@julonexus please review it

thanks

**Comment by soroshsabz** [comment]
@Viish Did you can review it?

thanks

**Comment by julonexus** [comment]
The fix was already inside other branchs. I merged the last one into master.

**Comment by soroshsabz** [comment]
Thanks from reply

I think merging step by step is better. (if you merge this PR, I remerge from this to another PR.)

thanks :)

**Comment by soroshsabz** [comment]
@julonexus Any update?

**Comment by julonexus** [comment]
Merged

**Pull request closed without merging**
