### PR TITLE
Add config file

### LINKED ISSUE #23: Add file based default configuration
ITNOA

I think it is very useful to add App.config for app to write many default configuration in text file and save many times for debug app.

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

This PR resolved #23

### CODE REVIEW

**Comment by soroshsabz** [comment]
@julonexus I resolve all conflicts.

thanks for review it :)

**Comment by julonexus** [comment]
Hi thanks for your contribution. Did you sign the contributor agreement like in https://gitlab.linphone.org/BC/public/linphone-desktop#code ?

**Comment by soroshsabz** [comment]
@julonexus Yes, I sign it and sent it to sales@belledonne-communications.com from my email address.

**Comment by soroshsabz** [comment]
@julonexus any update?

thanks

**Comment by soroshsabz** [comment]
@julonexus Any update?

thanks

**Comment by soroshsabz** [comment]
@julonexus Any update?

thanks

**Comment by soroshsabz** [comment]
@julonexus Any update?

thanks

**Comment by julonexus** [comment]
Merged.

**Comment by soroshsabz** [comment]
@julonexus Where is this merge? you closed this PR and codebase does not change yet.

thanks

**Comment by julonexus** [comment]
Check the Gitlab repository at https://gitlab.linphone.org/BC/public/linphone-windows10/-/commits/master/

**Pull request closed without merging**
